### ISSUE TITLE
Failed to start on express server

### ISSUE THREAD

**Issue by raitalharehman** [moovweb/react-storefront#75] opened 2019-02-11 04:57 UTC
**on yarn start:express command**
**error log**
exports = module.exports = createDebug.debug = createDebug['default'] = createDebug;
^

TypeError: Cannot assign to read only property 'exports' of object '#'

**Comment by markbrocato** [comment] 2019-02-11 12:51
I can't seem to reproduce that problem locally. What version of node are you using?  We recommend at least 8.11.  Perhaps try removing node_modules and package-lock.json and rerunning `npm install`?

**Comment by raitalharehman** [comment] 2019-02-12 05:19
using node v8.15.0 and i did try remove node_modules and lock file and rerunning npm i

**Comment by raitalharehman** [comment] 2019-02-12 05:27
same error even now using `8.11.0 `

**Comment by dijs** [comment] 2019-02-12 08:14
Are you using `module.exports` anywhere in your code?

Or is this error happening from a clean starter project from `create-react-storefront`?

**Comment by dijs** [comment] 2019-02-12 08:40
Never mind, I was able to reproduce.

**Comment by markbrocato** [comment] 2019-02-14 00:53
Ok, it looks like it was an issue in the starter app, not the framework.  It should be fixed by this commit: https://github.com/moovweb/react-storefront-boilerplate/commit/61a3888bcc9a37463f85506cee05844382fdf5a0

You can either create a new app or just remove that line from your babel.config.js

**Closed by markbrocato** 2019-02-14 00:53 UTC
